
services:
  php:
    container_name: ${CONTAINER_NAME}-php-fpm
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        LOCAL_USER: jose
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
  nginx:
    container_name: ${CONTAINER_NAME}-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
  redis:
    image: redis:latest